import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Topbar from "./components/Topbar";
import Header from "./components/Header";
import Bottom from "./components/Bottom";
import Footer from "./components/Footer";
import { CartProvider } from "./components/CartContext";

// ...existing code...

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Topbar/>
          <Header/>
          <Bottom/>
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
